class Unreadable:

  def __init__(self):
    self.code = {
    "A": "ሞ",
    "B": "ቇ",
    "C": "ↂ",
    "D": "∭",
    "E": "ↀ",
    "F": "⊝",
    "G": "Ṵ",
    "H": "ឿ",
    "I": "ቘ",
    "J": "ጬ",
    "K": "ൺ",
    "L": "'ో",
    "M": "ൕ",
    "N": "ᾟ",
    "O": "ᵿ",
    "P": "ᦛ",
    "Q": "᧿",
    "R": "ᙨ",
    "S": "ᕱ",
    "T": "ᣧ",
    "U": "ᣤ",
    "V": "ᢷ",
    "W": "៘",
    "X": "ឪ",
    "Y": "ᘓ",
    "Z": "ᘲ",
    " ": " ",
    "!": "!",
    "?": "?",
    ".": ".",
    ",": ",",
    "(": "(",
    ")":")",
    "<": "<",
    ">": ">",
    "'": "'",
    "\"": "\"",
    ":": ":",
    ";": ";",
    "-": "-",
    "_": "_",
    "[": "[",
    "{": "{",
    "]": "]",
    "}": "}",
    "+": "+",
    "=": "=",
    "|": "|",
    "`": "`",
    "~": "~",
    "@": "@",
    "#": "#",
    "$": "$",
    "%": "%",
    "^": "^",
    "&": "&",
    "*": "*",
    "/": "/"
    }
 
  def decipher(self, mode, phrase):
    if mode.lower() == 'encode':
      return "".join([self.code[i] for i in phrase.upper()])
    elif mode.lower() == 'decode':
      decoded = {v:k for k, v in self.code.items()} 
      return "".join([decoded[x] for x in phrase.upper()])
